sudo: false
language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: '1.9'
    bundler_args: '--no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}'
  - rvm: '2.1'
  - rvm: '2.3'
  - rvm: '2.4'
before_install: gem install bundler -v 1.15.1
